services:
  mgba-test:
    image: ghcr.io/johndeved/pokemon-save-web/mgba-test-env:latest
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: mgba-test-environment
    ports:
      - "7102:7102"
    environment:
      - DISPLAY=:99
      - QT_QPA_PLATFORM=xcb
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7102/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    volumes:
      - ../src/lib/parser/__tests__/test_data:/app/data:rw
      - ../scripts/mgba-lua/http-server.lua:/app/data/mgba_http_server.lua:ro