services:
  mgba-test:
    # Use pre-built image from GHCR if available, otherwise build locally
    image: ${MGBA_IMAGE:-ghcr.io/johndeved/pokemon-save-web/mgba-test-env:latest}
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: mgba-test-environment
    ports:
      - "7102:7102"
    environment:
      - DISPLAY=:99
      - QT_QPA_PLATFORM=xcb
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7102/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s